"""watchlist owner required with admin backfill

Revision ID: e9666efb6bf6
Revises: e40b4a4c320c
Create Date: 2026-09-14 12:31:50.257025
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e9666efb6bf6'
down_revision: str | None = 'e40b4a4c320c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Backfill pre-existing (global) watchlists to the first admin before the
    # NOT NULL lands. Deploy order: migrate A -> seed_admin -> this revision.
    conn = op.get_bind()
    admin_id = conn.execute(
        sa.text(
            "SELECT id FROM users WHERE role = 'admin' ORDER BY id LIMIT 1"
        )
    ).scalar()
    if admin_id is None:
        raise RuntimeError(
            "No admin user found: run "
            "`ADMIN_EMAIL=... ADMIN_PASSWORD=... python -m app.seed_admin` "
            "before this migration"
        )
    conn.execute(
        sa.text("UPDATE watchlists SET owner_id = :admin WHERE owner_id IS NULL"),
        {"admin": admin_id},
    )
    op.alter_column('watchlists', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchlists', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
