"""Initial migration - create all tables

Revision ID: fa552d8fed5f
Revises: 
Create Date: 2026-09-02 10:26:33.642675
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa552d8fed5f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed',
              name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    op.create_index('ix_jobs_celery_task_id', 'jobs', ['celery_task_id'], unique=True)
    op.create_index('ix_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.Enum('manual', 'sync', name='moviesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imdb_id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_index('ix_movies_imdb_id', 'movies', ['imdb_id'], unique=True,
                    postgresql_where='imdb_id IS NOT NULL')
    op.create_index('ix_movies_source', 'movies', ['source'], unique=False)
    op.create_index('ix_movies_title', 'movies', ['title'], unique=False)
    op.create_index('ix_movies_tmdb_id', 'movies', ['tmdb_id'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.BigInteger(), nullable=False),
    sa.Column('movie_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('to_watch', 'watched', name='watchliststatus'),
              nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True),
              server_default=sa.text('now()'), nullable=False),
    sa.Column('watched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'movie_id',
                        name='uq_watchlist_entries_watchlist_movie')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_entries')
    op.drop_table('watchlists')
    op.drop_index('ix_movies_tmdb_id', table_name='movies')
    op.drop_index('ix_movies_title', table_name='movies')
    op.drop_index('ix_movies_source', table_name='movies')
    op.drop_index('ix_movies_imdb_id', table_name='movies',
                   postgresql_where='imdb_id IS NOT NULL')
    op.drop_table('movies')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_job_type', table_name='jobs')
    op.drop_index('ix_jobs_celery_task_id', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
